function [ err ] = error()
mode = struct('WindowStyle','non-modal', 'Interpreter','tex');
err = errordlg({'Try to type instead:', ...
    'Map("Load")', ...
    'Map("Load", #landamark)', ...
    'Map("Load", #landamark, "auto")', ...
    'Map("Load", #landamark, "manual")', ...
    'Map("New", width, heigth)', ...
    'Map("New", width, heigth, #landmark, "auto")', ...
    'Map("New", width, heigth, #landmark, "manual")'}, ...
    'Error Map generator', mode);
end